language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: peden.jc@gmail.com
  password:
    secure: XmBXRgDBFeteDfdSL/ixpISQRvhl881S4YmN/Al8+aXpDsOvXEml0eg0TneT0lBubAJih2NnB81Szlb9npzjD/ipODHOnCLBO2+9BSUJUqcPX6bGZY7/VCMwDnlPKdQLDX0fPyipqpjNBQBqkzLV7dZNSAvgWGLchsPNI7PWzUI=
  app: creditcard
  domain: ccairlinepoints
  on:
    repo: jcpeden/creditcardairlinepoints
after_success:
- cd dist
- git init
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -am "Travis change"
